<?php
namespace TheWebsiteGuy\FormWizard\Classes\Traits;

use Lang;

trait SharedProperties
{
    public function defineProperties()
    {
        return [
            'group' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.group.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.group.description',
                'type' => 'string',
                'showExternalParam' => false,
            ],
            'uploader_enable' => [
                'title' => 'Allow file uploads',
                'description' => 'Enable file attachments via FilePond.',
                'type' => 'checkbox',
                'default' => false,
                'showExternalParam' => false,
            ],
            'rules' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.rules.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.rules.description',
                'type' => 'dictionary',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_validation',
                'showExternalParam' => false,
            ],
            'rules_messages' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.rules_messages.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.rules_messages.description',
                'type' => 'dictionary',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_validation',
                'showExternalParam' => false,
            ],
            'custom_attributes' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.custom_attributes.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.custom_attributes.description',
                'type' => 'dictionary',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_validation',
                'showExternalParam' => false,
            ],
            'messages_success' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.messages_success.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.messages_success.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_messages',
                'default' => Lang::get('thewebsiteguy.formwizard::lang.components.shared.messages_success.default'),
                'showExternalParam' => false,
                'validation' => ['required' => ['message' => Lang::get('thewebsiteguy.formwizard::lang.components.shared.validation_req')]],
            ],
            'messages_errors' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.messages_errors.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.messages_errors.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_messages',
                'default' => Lang::get('thewebsiteguy.formwizard::lang.components.shared.messages_errors.default'),
                'showExternalParam' => false,
                'validation' => ['required' => ['message' => Lang::get('thewebsiteguy.formwizard::lang.components.shared.validation_req')]],
            ],
            'messages_partial' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.messages_partial.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.messages_partial.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_messages',
                'showExternalParam' => false,
            ],
            'mail_enabled' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_enabled.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_enabled.description',
                'type' => 'checkbox',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_subject' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_subject.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_subject.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_recipients' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_recipients.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_recipients.description',
                'type' => 'stringList',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_bcc' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_bcc.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_bcc.description',
                'type' => 'stringList',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_replyto' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_replyto.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_replyto.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_template' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_template.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_template.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail',
                'showExternalParam' => false,
            ],
            'mail_resp_enabled' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_enabled.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_enabled.description',
                'type' => 'checkbox',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'mail_resp_field' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_field.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_field.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'mail_resp_name' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_name.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_name.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'mail_resp_from' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_from.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_from.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'mail_resp_subject' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_subject.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_resp_subject.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'mail_resp_template' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.mail_template.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.mail_template.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_mail_resp',
                'showExternalParam' => false,
            ],
            'reset_form' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.reset_form.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.reset_form.description',
                'type' => 'checkbox',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_settings',
                'showExternalParam' => false,
            ],
            'redirect' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.redirect.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.redirect.description',
                'type' => 'string',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_settings',
                'showExternalParam' => false,
            ],
            'inline_errors' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.inline_errors.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.inline_errors.description',
                'type' => 'dropdown',
                'options' => ['disabled' => 'thewebsiteguy.formwizard::lang.components.shared.inline_errors.disabled', 'display' => 'thewebsiteguy.formwizard::lang.components.shared.inline_errors.display', 'variable' => 'thewebsiteguy.formwizard::lang.components.shared.inline_errors.variable'],
                'default' => 'disabled',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_settings',
                'showExternalParam' => false,
            ],
            'js_on_success' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.js_on_success.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.js_on_success.description',
                'type' => 'text',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_settings',
                'showExternalParam' => false,
            ],
            'js_on_error' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.js_on_error.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.js_on_error.description',
                'type' => 'text',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_settings',
                'showExternalParam' => false,
            ],
            'allowed_fields' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.allowed_fields.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.allowed_fields.description',
                'type' => 'stringList',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_security',
                'showExternalParam' => false,
            ],
            'sanitize_data' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.sanitize_data.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.sanitize_data.description',
                'type' => 'dropdown',
                'options' => ['disabled' => 'thewebsiteguy.formwizard::lang.components.shared.sanitize_data.disabled', 'htmlspecialchars' => 'thewebsiteguy.formwizard::lang.components.shared.sanitize_data.htmlspecialchars'],
                'default' => 'disabled',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_security',
                'showExternalParam' => false,
            ],
            'anonymize_ip' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.anonymize_ip.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.anonymize_ip.description',
                'type' => 'dropdown',
                'options' => ['disabled' => 'thewebsiteguy.formwizard::lang.components.shared.anonymize_ip.disabled', 'partial' => 'thewebsiteguy.formwizard::lang.components.shared.anonymize_ip.partial', 'full' => 'thewebsiteguy.formwizard::lang.components.shared.anonymize_ip.full'],
                'default' => 'disabled',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_security',
                'showExternalParam' => false,
            ],
            'recaptcha_enabled' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_enabled.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_enabled.description',
                'type' => 'checkbox',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_recaptcha',
                'showExternalParam' => false,
            ],
            'recaptcha_theme' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_theme.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_theme.description',
                'type' => 'dropdown',
                'options' => ['light' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_theme.light', 'dark' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_theme.dark'],
                'default' => 'light',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_recaptcha',
                'showExternalParam' => false,
            ],
            'recaptcha_type' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_type.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_type.description',
                'type' => 'dropdown',
                'options' => ['image' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_type.image', 'audio' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_type.audio'],
                'default' => 'image',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_recaptcha',
                'showExternalParam' => false,
            ],
            'recaptcha_size' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_size.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_size.description',
                'type' => 'dropdown',
                'options' => [
                    'normal' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_size.normal',
                    'compact' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_size.compact',
                    'invisible' => 'thewebsiteguy.formwizard::lang.components.shared.recaptcha_size.invisible',
                ],
                'default' => 'normal',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_recaptcha',
                'showExternalParam' => false,
            ],
            'skip_database' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.skip_database.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.skip_database.description',
                'type' => 'checkbox',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_advanced',
                'showExternalParam' => false,
            ],
            'emails_date_format' => [
                'title' => 'thewebsiteguy.formwizard::lang.components.shared.emails_date_format.title',
                'description' => 'thewebsiteguy.formwizard::lang.components.shared.emails_date_format.description',
                'default' => 'Y-m-d',
                'group' => 'thewebsiteguy.formwizard::lang.components.shared.group_advanced',
                'showExternalParam' => false,
            ],
        ];
    }
}
